spring.application.name=marketBot

server.port=8080

# External API timeout
external-api.connect-timeout=3s
external-api.read-timeout=5s

# =========================================================
# Slack
# =========================================================
slack.bot.token=
slack.signing-secret=
slack.workspace=
slack.digest.channel-id=


# =========================================================
# Notion
# =========================================================
notion.token=
notion.database.id=
notion.version=

# =========================================================
# MySQL
# =========================================================
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
