spring.application.name=WorkTrace

server.port=8081

# =========================================================
# Slack
# =========================================================

slack.bot.token=${SLACK_BOT_TOKEN}
slack.signing-secret=${SLACK_SIGNING_SECRET}

# =========================================================
# Notion
# =========================================================

notion.api.token=${NOTION_API_TOKEN}
notion.data-source-id=${NOTION_DATA_SOURCE_ID}
